### ISSUE TITLE
acme crashes when displaying some characters

### ISSUE THREAD

**Issue by rogpeppe** [9fans/plan9port#125] opened 2017-11-17 15:04 UTC
I'm using the Go font like this:

    fontsrv &
    $PLAN9/bin/acme -f '/mnt/font/Go Regular/13a/font' -a $*

when I view $PLAN9/lib/keyboard (and other files with unicode or
binary characters), acme crashes with:

    acme: end of string in frcharofpt: No such file or directory

a) it should be more resilient to bad fonts
b) it should at least do a Dump before exiting, so work is not lost.

**Comment by rsc** [comment] 2020-01-16 17:16
48da9bd is supposed to fix this on x11, and I can't reproduce on macOS, so closing.

**Closed by rsc** 2020-01-16 17:16 UTC
