### ISSUE TITLE
[Linux] Installing failed:  did you mean ‘d_name’

### ISSUE THREAD

**Issue by nasirhm** [9fans/plan9port#399] opened 2020-05-18 19:20 UTC
Here are the logs, While running `./INSTALL` : 

``` * Resetting /config
* Compiler version:
	gcc version 10.1.1 20200507 (Red Hat 10.1.1-1) (GCC) 
* Building mk...
>>> cd /home/nasirhm/Documents/Plan9/src/lib9
9c open.c
open.c:321:21: error: ‘struct dirent’ has no member named ‘d_namlen’; did you mean ‘d_name’?
  321 |   if(de->d_name[de->d_namlen] != 0)
      |                     ^~~~~~~~
      |                     d_name
>>> cd /home/nasirhm/Documents/Plan9/src/lib9
9ar rsc /home/nasirhm/Documents/Plan9/lib/lib9.a _exits.o _p9dialparse.o _p9dir.o announce.o argv0.o atexit.o atoi.o atol.o atoll.o atnotify.o await.o cistrcmp.o cistrncmp.o cistrstr.o cleanname.o convD2M.o convM2D.o convM2S.o convS2M.o crypt.o ctime.o dial.o dirfstat.o dirfwstat.o dirmodefmt.o dirstat.o dirwstat.o dup.o encodefmt.o errstr.o exec.o execl.o exitcode.o fcallfmt.o frand.o get9root.o getcallerpc.o getenv.o getfields.o getnetconn.o getns.o getuser.o getwd.o jmp.o lrand.o lnrand.o main.o malloc.o malloctag.o mallocz.o nan.o needsrcquote.o needstack.o netcrypt.o netmkaddr.o notify.o nrand.o nulldir.o open.o opentemp.o pin.o pipe.o post9p.o postnote.o qlock.o quote.o rand.o read9pmsg.o readcons.o readn.o rfork.o searchpath.o sendfd.o sleep.o strdup.o strecpy.o sysfatal.o syslog.o sysname.o time.o tm2sec.o tokenize.o truerand.o u16.o u32.o u64.o unsharp.o wait.o waitpid.o write.o zoneinfo.o dofmt.o fltfmt.o fmt.o fmtfd.o fmtfdflush.o fmtlocale.o fmtlock2.o fmtnull.o fmtprint.o fmtquote.o fmtrune.o fmtstr.o fmtvprint.o fprint.o frexp.o nan64.o print.o runefmtstr.o runeseprint.o runesmprint.o runesnprint.o runesprint.o runevseprint.o runevsmprint.o runevsnprint.o seprint.o smprint.o snprint.o sprint.o strtod.o vfprint.o vseprint.o vsmprint.o vsnprint.o charstod.o pow10.o rune.o runestrcat.o runestrchr.o runestrcmp.o runestrcpy.o runestrdup.o runestrlen.o runestrecpy.o runestrncat.o runestrncmp.o runestrncpy.o runestrrchr.o runestrstr.o runetype.o utfecpy.o utflen.o utfnlen.o utfrrune.o utfrune.o utfutf.o
ar: open.o: No such file or directory
>>> cd /home/nasirhm/Documents/Plan9/src/cmd/mk
9l -o o.mk arc.o archive.o bufblock.o env.o file.o graph.o job.o lex.o main.o match.o mk.o parse.o recipe.o rc.o rule.o run.o sh.o shell.o shprint.o symtab.o var.o varsub.o word.o unix.o
/bin/ld: cannot find -l9
collect2: error: ld returned 1 exit status
>>> cd /home/nasirhm/Documents/Plan9/src/cmd/mk
install o.mk /home/nasirhm/Documents/Plan9/bin/mk
install: cannot stat 'o.mk': No such file or directory
* Error: mk failed to build.
 ```

Planning to use Acme on Fedora 32.

**Comment by gdiazlo** [comment] 2020-05-18 20:49
This is a duplicate of #395

**Comment by rsc** [comment] 2020-05-18 21:04
Fixed.

**Closed by rsc** 2020-05-18 21:04 UTC

**Comment by nasirhm** [comment] 2020-05-19 16:51
Thanks @gdiazlo & @rsc
