### ISSUE TITLE
devdraw: After MacOS Mojave update Acme window remains gray

### ISSUE THREAD

**Issue by palmamartin** [9fans/plan9port#185] opened 2018-09-26 08:05 UTC
Hello,
sorry for the noise but after upgrading to MacOS Mojave and rebuilding plan9port my Acme window remains gray. Windows resizing didn't help either...  See:

<img width="968" alt="screenshot 2018-09-26 at 09 45 39" src="https://user-images.githubusercontent.com/381/46065030-4fdaba80-c171-11e8-93c0-748b3ab63e41.png">

Any suggestions?

**Comment by mazebuhu** [comment] 2018-09-26 08:40
Find here some logs with backtrace of devdraw when starting acme: [https://gist.github.com/mazebuhu/5ae3cf2c3d5144ff46df571a6bd949da](https://gist.github.com/mazebuhu/5ae3cf2c3d5144ff46df571a6bd949da)

**Comment by mjl-** [comment] 2018-09-26 08:48
can confirm. just did a fresh plan9port build from a fresh git clone on mojave. devdraw only shows a gray screen.

**Comment by jxy** [comment] 2018-09-26 14:13
Yes.  I have the same problem.  Maybe we need to use `-drawRect` and remove the custom scheduling of refresh.

**Comment by mjl-** [comment] 2018-09-26 15:36
true, the problem is with binaries compiled on mojave. before i rebuilt, i had binaries from the previous macos release, and those still worked on mojave.

so don't yet recompile after updating to mojave. (:

btw, i'm using lato as acme font, and thought was it looked worse. which may have triggered me to pull latest plan9port and recompile.

**Comment by mazebuhu** [comment] 2018-09-26 15:48
Yes binaries build pre Mojave will work. The issue occurs only after a
rebuild or a build from scratch on Mojave.

**Comment by jxy** [comment] 2018-09-26 18:34
I copied `devdraw` only from the time machine and everything else works.  @mazebuhu perhaps you can change the title to mention `devdraw` instead.

**Comment by iburago** [comment] 2018-09-27 07:10
@kare @jxy Would you mind sharing a copy of the `devdraw` binary
built on High Sierra for those of us who do not have it and need to do
a fresh install on Mojave (as opposed to rebuilding after updating to it)?

**Comment by mazebuhu** [comment] 2018-09-27 07:27
@iburago find mine here: https://drive.google.com/file/d/1L9gig6UdGErLeoNb7BhFMQLnhczMGDh3/view?usp=sharing

**Comment by iburago** [comment] 2018-09-27 07:38
@mazebuhu Thank you!

**Comment by jacobvosmaer** [comment] 2018-10-03 21:49
It seems to go wrong in [cocoa-screen.m](https://github.com/9fans/plan9port/blob/93c75d2bad341af383520409fd354dcff3f2c279/src/cmd/devdraw/cocoa-screen.m#L688). `[WIN graphicsContext]` returns NULL. `WIN` itself is non-null.

It doesn't help that calling `graphicsContext` on an `NSWindow` is deprecated. Don't know enough about macos graphics programming to make more of this.

**Comment by jacobvosmaer** [comment] 2018-10-04 07:33
https://developer.apple.com/videos/play/wwdc2018/209/

"What's new in Cocoa for macOS (10.14)", slide 122.

> Obsolete Patterns
`-[NSWindow graphicsContext]` / `+[NSGraphicsContext graphicsContextWithWindow:]`
 Just subclass NSView and implement `.draw()`

**Comment by jacobvosmaer** [comment] 2018-10-05 22:43
Anybody here want to try out the devdraw executable from https://github.com/9fans/plan9port/pull/188 ?

I've tested it briefly on 10.13 and 10.14, it seems to mostly work but I see some rough edges. I'm sure I've created bugs, it would help to know what they are.

**Comment by jacobvosmaer** [comment] 2018-10-10 07:52
I have cleaned up my patch and re-submitted it as #191.

**Comment by jacobvosmaer** [comment] 2018-11-14 15:46
You can use commits from #194 (or #191) to get code that creates a working devdraw.

**Comment by rsc** [comment] 2018-11-14 22:09
@4ad Probably tomorrow, decent Mojave support will be checked in. It's a more complicated update than you'd hope.

**Comment by rsc** [comment] 2018-11-16 01:52
Everyone having trouble on Mojave, please `git pull -r` and try again. Things should be much better, with all the credit going to @jacobvosmaer and @jxy. Thanks very much!

**Closed by rsc** 2018-11-16 01:52 UTC

**Comment by 4ad** [comment] 2018-11-16 15:00
Fantastic, thanks. It appears that the full screen bug is still not solved? I need to click on the screen in order to be rendered. Also, do we really want to sue the Plan 9 cursor?

**Comment by 4ad** [comment] 2018-11-16 15:02
Also, I've found another bug. When in full screen mode, when switching desktops, sometimes when switching back to acme the screen will flicker to black when I click.

**Comment by rsc** [comment] 2018-11-16 16:54
> Fantastic, thanks. It appears that the full screen bug is still not solved? I need to click on the screen in order to be rendered.

Indeed. I filed #208 to track it, although I doubt we will forget. Debugging help and patches are always welcome.

> Also, do we really want to use the Plan 9 cursor?

Now that it's decent resolution I think it looks fine and I'd like to keep it for a while.

> When in full screen mode, when switching desktops, sometimes when switching back to acme the screen will flicker to black when I click on it.

Thanks for filing #207 for that.

**Comment by otremblay** [comment] 2019-01-14 18:45
Hi, I'm running High Sierra and I can't get `master` to work (I get this issue).
https://github.com/9fans/plan9port/pull/191 <- this works for me.
Am I doing something wrong? I've just been running `./INSTALL`.
