### ISSUE TITLE
stats(1) deadlocks at initdraw

### ISSUE THREAD

**Issue by fhs** [9fans/plan9port#171] opened 2018-06-16 06:42 UTC
I was able to reduce `stats(1)` to the following program that reproduces the deadlock. If you move the `proccreate` to after `initdraw`, you don't get the deadlock.
```
#include <u.h>
#include <libc.h>
#include <draw.h>
#include <thread.h>

void machproc(void *v) {}

void threadmain(int argc, char *argv[]) {
	proccreate(machproc, nil, 8192);

print("calling initdraw...\n");
	if(initdraw(0, nil, "stats") < 0)
		sysfatal("initdraw: %r");
print("initdraw done\n");

	closedisplay(display);
	threadexitsall("");
}
```
Run it in a loop to get the deadlock:
```
$ 9c stats.c && 9l -o stats stats.o
$ while :; do ./stats; done
calling initdraw...
```
Stacktrace:
```
$ ps aux|grep stats
fhs       2658  0.0  0.0  14320  1276 pts/12   S+   02:28   0:00 ./stats
fhs       2659  0.0  0.0  90588   424 pts/12   S+   02:28   0:00 ./stats
fhs       2661  0.0  0.0  88704   172 pts/12   S+   02:28   0:00 ./stats
$ sudo gdb -pid 2658
Attaching to process 2658
Reading symbols from /home/fhs/tmp/stats...done.
Reading symbols from /usr/lib/libm.so.6...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libutil.so.1...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libresolv.so.2...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Reading symbols from /usr/lib/libc.so.6...(no debugging symbols found)...done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
0x00007fe2272a14de in read () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007fe2272a14de in read () from /usr/lib/libpthread.so.0
#1  0x0000562f42c0a2e5 in _threadsetupdaemonize () at daemonize.c:151
#2  0x0000562f42c09ef5 in p9main (argc=1, argv=0x7ffdecef9ae8) at thread.c:721
#3  0x0000562f42bfe979 in main (argc=<optimized out>, argv=<optimized out>) at main.c:10
(gdb) q
$ sudo gdb -pid 2659
Attaching to process 2659
Reading symbols from /home/fhs/tmp/stats...done.
Reading symbols from /usr/lib/libm.so.6...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libutil.so.1...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libresolv.so.2...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Reading symbols from /usr/lib/libc.so.6...(no debugging symbols found)...done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libgcc_s.so.1...done.
0x00007fe2272a1514 in read () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007fe2272a1514 in read () from /usr/lib/libpthread.so.0
#1  0x0000562f42c0c2ba in readn (f=3, av=av@entry=0x7fe227e811c4, n=n@entry=4) at readn.c:12
#2  0x0000562f42c02e1d in _drawrecv (canblock=canblock@entry=1, vp=vp@entry=0x7fe227e81210, mux=<optimized out>)
    at drawclient.c:115
#3  0x0000562f42c02f09 in drawrecv (mux=<optimized out>) at drawclient.c:136
#4  0x0000562f42c07d06 in _muxrecv (mux=mux@entry=0x562f438f20e0, canblock=canblock@entry=1, 
    vp=vp@entry=0x7fe227e81290) at io.c:98
#5  0x0000562f42c077b7 in muxrpc (mux=0x562f438f20e0, tx=tx@entry=0x562f438f22c0) at mux.c:141
#6  0x0000562f42c02fb8 in displayrpc (tx=tx@entry=0x7fe227e81320, rx=rx@entry=0x7fe227e813e0, 
    freep=freep@entry=0x0, d=<optimized out>) at drawclient.c:209
#7  0x0000562f42c0338b in _displayinit (d=d@entry=0x562f438e1f80, label=label@entry=0x562f42c12cf9 "stats", 
    winsize=<optimized out>) at drawclient.c:252
#8  0x0000562f42bff568 in _initdisplay (error=error@entry=0x0, label=0x562f42c12cf9 "stats") at init.c:278
#9  0x0000562f42bff6cc in geninitdraw (devdir=devdir@entry=0x562f42c12dd8 "/dev", error=error@entry=0x0, 
    fontname=fontname@entry=0x0, label=<optimized out>, label@entry=0x562f42c12cf9 "stats", 
    windir=windir@entry=0x562f42c12dd8 "/dev", ref=ref@entry=1) at init.c:49
#10 0x0000562f42bffbee in initdraw (error=error@entry=0x0, fontname=fontname@entry=0x0, 
    label=label@entry=0x562f42c12cf9 "stats") at init.c:130
#11 0x0000562f42bfeac5 in threadmain (argc=<optimized out>, argv=<optimized out>) at stats.c:12
#12 0x0000562f42c099bd in threadstart (y=<optimized out>, x=<optimized out>) at thread.c:96
#13 0x00007fe226f20e40 in __correctly_grouped_prefixwc () from /usr/lib/libc.so.6
#14 0x0000000000000000 in ?? ()
(gdb) q
$ sudo gdb -pid 2661
Attaching to process 2661
Reading symbols from /home/fhs/tmp/stats...done.
Reading symbols from /usr/lib/libm.so.6...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libutil.so.1...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libresolv.so.2...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Reading symbols from /usr/lib/libc.so.6...(no debugging symbols found)...done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
0x00007fe2272a129c in __lll_lock_wait () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007fe2272a129c in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007fe22729a7c4 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#2  0x0000562f42c080a8 in _threadlock () at pthread.c:32
#3  0x0000562f42c0bd90 in lock (l=<optimized out>, l@entry=0x562f42e1c6e0 <malloclock>) at qlock.c:25
#4  0x0000562f42c0b644 in p9malloc (n=n@entry=32) at malloc.c:19
#5  0x0000562f42c0fd12 in fmtstrinit (f=f@entry=0x7fe227e812d0) at fmt/vsmprint.c:52
#6  0x0000562f42c0fd99 in vsmprint (fmt=0x562f42c13f13 "%s=%s", args=args@entry=0x7fe227e81390)
    at fmt/vsmprint.c:73
#7  0x0000562f42c0f9fd in smprint (fmt=fmt@entry=0x562f42c13f13 "%s=%s") at fmt/smprint.c:14
#8  0x0000562f42c0b608 in p9putenv (s=s@entry=0x562f42c13205 "NOLIBTHREADDAEMONIZE", 
    v=v@entry=0x562f42c14daa "1") at getenv.c:21
#9  0x0000562f42c03212 in _displayconnect (d=d@entry=0x562f438e1f80) at drawclient.c:58
#10 0x0000562f42bff54e in _initdisplay (error=error@entry=0x0, label=0x562f42c12cf9 "stats") at init.c:278
#11 0x0000562f42bff6cc in geninitdraw (devdir=devdir@entry=0x562f42c12dd8 "/dev", error=error@entry=0x0, 
    fontname=fontname@entry=0x0, label=<optimized out>, label@entry=0x562f42c12cf9 "stats", 
    windir=windir@entry=0x562f42c12dd8 "/dev", ref=ref@entry=1) at init.c:49
#12 0x0000562f42bffbee in initdraw (error=error@entry=0x0, fontname=fontname@entry=0x0, 
    label=label@entry=0x562f42c12cf9 "stats") at init.c:130
#13 0x0000562f42bfeac5 in threadmain (argc=<optimized out>, argv=<optimized out>) at stats.c:12
#14 0x0000562f42c099bd in threadstart (y=<optimized out>, x=<optimized out>) at thread.c:96
#15 0x00007fe226f20e40 in __correctly_grouped_prefixwc () from /usr/lib/libc.so.6
#16 0x0000000000000000 in ?? ()
(gdb) q
```

**Comment by rsc** [comment] 2020-01-16 16:58
Closing as duplicate of #349, which @dancrossnyc is working on.

**Closed by rsc** 2020-01-16 16:58 UTC
