### ISSUE TITLE
Unicode input outwith BMP not working

### ISSUE THREAD

**Issue by nelk114** [9fans/plan9port#393] opened 2020-05-08 15:38 UTC
Inputting characters outwith the Basic Multilingual Plane is broken, at least on X11. Typing high characters (using a custom xkb layout as it doesn't look like `mklatinkbd` handles code points outwith BMP) projects the character onto the BMP (e.g. typing U+1D15F ⟨𝅘𝅥⟩ gives U+D15F ⟨텟⟩).

The command-line tools handle unicode without issue afaict (at least `sam -d` running in a normal terminal emulator such as `st` works as expected) so I suspect it's a graphics library issue.

**Comment by rsc** [comment] 2020-05-18 21:45
The problem is that the graphics RPC protocol sends only 16-bit runes. It needs to be expanded. I haven't decided if I want to expand to 32-bit runes or start sending multi-rune UTF8 strings. Probably the latter. I've been doing some work on the protocol recently and may be able to do this sooner rather than later.

**Comment by rsc** [comment] 2020-05-19 03:47
Fixed in d25d0ca1.

**Closed by rsc** 2020-05-19 03:47 UTC
